import { useState, useEffect } from "react";
import { useUser } from "@clerk/clerk-react";
import Navbar from "@/components/Navbar";
import FooterSection from "@/components/FooterSection";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { usePatient } from "@/hooks/usePatient";
import {
  Lightbulb, Pill, Activity, HeartPulse, MonitorSmartphone,
  AlertTriangle, Loader2, FileText, RotateCcw, ShoppingBag,
  ChevronRight, Sparkles
} from "lucide-react";

interface RecItem {
  name: string;
  reason: string;
  priority: "High" | "Medium" | "Low";
}

interface RecCategory {
  category: string;
  items: RecItem[];
}

interface RecommendationsData {
  overall_summary: string;
  recommendations: RecCategory[];
}

const priorityColor = (p: string) => {
  switch (p) {
    case "High":   return "bg-red-500/10 text-red-400 border-red-500/20";
    case "Medium": return "bg-yellow-500/10 text-yellow-400 border-yellow-500/20";
    case "Low":    return "bg-green-500/10 text-green-400 border-green-500/20";
    default:       return "bg-secondary/40 text-muted-foreground border-border";
  }
};

const categoryIcon = (cat: string) => {
  const c = cat.toLowerCase();
  if (c.includes("supplement") || c.includes("vitamin")) return <Pill className="h-5 w-5" />;
  if (c.includes("otc") || c.includes("medication")) return <HeartPulse className="h-5 w-5" />;
  if (c.includes("device") || c.includes("monitor")) return <MonitorSmartphone className="h-5 w-5" />;
  if (c.includes("lifestyle") || c.includes("wellness")) return <Activity className="h-5 w-5" />;
  return <ShoppingBag className="h-5 w-5" />;
};

export default function Recommendations() {
  const { user } = useUser();
  const { userId, patientName, authHeaders, API } = usePatient();
  const { toast } = useToast();

  const [data, setData] = useState<RecommendationsData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchRecommendations = async () => {
    if (!userId) return;
    setLoading(true);
    setError(null);
    setData(null);

    try {
      const headers = await authHeaders();
      const res = await fetch(`${API}/recommendations/${userId}`, { headers });

      if (res.status === 404) {
        setError("No medical reports found yet. Upload a report first to get personalized recommendations.");
        return;
      }
      if (!res.ok) throw new Error("Failed to load recommendations.");

      const json = await res.json();
      setData(json);
    } catch (e: any) {
      setError(e.message || "Something went wrong");
      toast({ title: "Error", description: e.message, variant: "destructive" });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (userId) fetchRecommendations();
  }, [userId]);

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Navbar />
      <main className="flex-1 pt-24 pb-12">
        <div className="container mx-auto px-6 max-w-6xl">

          {/* Header */}
          <div className="mb-10 flex flex-col md:flex-row items-start md:items-center justify-between gap-4 animate-fade-in-up">
            <div>
              <h1 className="text-3xl md:text-4xl font-bold text-foreground mb-2">
                Smart <span className="gradient-text">Recommendations</span>
              </h1>
              <p className="text-muted-foreground max-w-xl">
                Personalized medicinal and healthcare product recommendations based on your uploaded medical reports.
              </p>
            </div>
            <Button onClick={fetchRecommendations} disabled={loading} className="gradient-bg rounded-full px-6">
              <RotateCcw className={`h-4 w-4 mr-2 ${loading ? "animate-spin" : ""}`} />
              Refresh
            </Button>
          </div>

          {/* Disclaimer */}
          <div className="mb-8 glass border border-yellow-500/20 rounded-xl p-4 flex items-start gap-3 animate-fade-in-up">
            <AlertTriangle className="h-5 w-5 text-yellow-400 shrink-0 mt-0.5" />
            <div>
              <p className="text-sm text-yellow-400 font-medium">Medical Disclaimer</p>
              <p className="text-xs text-muted-foreground mt-1 leading-relaxed">
                These recommendations are generated by AI based on your uploaded reports and are for informational purposes only.
                They do not constitute medical advice, diagnosis, or treatment. Always consult a qualified healthcare professional before purchasing or consuming any medication, supplement, or medical device.
              </p>
            </div>
          </div>

          {/* Loading */}
          {loading && (
            <div className="text-center py-20 animate-fade-in-up">
              <div className="inline-flex items-center gap-3">
                <Loader2 className="h-8 w-8 text-primary animate-spin" />
                <span className="text-muted-foreground animate-pulse">Analyzing your reports and generating recommendations…</span>
              </div>
            </div>
          )}

          {/* Empty / Error state */}
          {!loading && error && (
            <div className="glass card-shadow rounded-2xl p-10 text-center animate-fade-in-up">
              <FileText className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
              <p className="text-muted-foreground text-lg mb-4">{error}</p>
              <Button asChild className="gradient-bg rounded-full px-8">
                <a href="/medical-report">
                  Upload Medical Report <ChevronRight className="ml-2 h-4 w-4" />
                </a>
              </Button>
            </div>
          )}

          {/* Content */}
          {!loading && data && (
            <div className="space-y-8 animate-fade-in-up">

              {/* Overall summary */}
              <div className="glass card-shadow rounded-2xl p-6">
                <div className="flex items-center gap-2 mb-4">
                  <Sparkles className="h-5 w-5 text-primary" />
                  <h3 className="text-lg font-semibold text-foreground">AI Summary</h3>
                  <span className="ml-auto text-xs text-muted-foreground bg-secondary/40 px-3 py-1 rounded-full">
                    Based on your reports
                  </span>
                </div>
                <p className="text-muted-foreground leading-relaxed whitespace-pre-line">
                  {data.overall_summary}
                </p>
              </div>

              {/* Category cards */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {data.recommendations.map((cat, i) => (
                  <div
                    key={i}
                    className="glass card-shadow rounded-2xl p-6 transition-all hover:-translate-y-1"
                    style={{ animationDelay: `${i * 100}ms` }}
                  >
                    <div className="flex items-center gap-3 mb-5">
                      <div className="p-2.5 rounded-xl bg-primary/10 text-primary">
                        {categoryIcon(cat.category)}
                      </div>
                      <h3 className="text-lg font-semibold text-foreground">{cat.category}</h3>
                    </div>

                    <ul className="space-y-4">
                      {cat.items.map((item, j) => (
                        <li key={j} className="flex items-start gap-3">
                          <Lightbulb className="h-4 w-4 text-primary shrink-0 mt-0.5" />
                          <div className="flex-1">
                            <div className="flex items-center gap-2 flex-wrap">
                              <span className="font-medium text-foreground">{item.name}</span>
                              <span className={`text-[10px] uppercase tracking-wide font-semibold px-2 py-0.5 rounded-full border ${priorityColor(item.priority)}`}>
                                {item.priority}
                              </span>
                            </div>
                            <p className="text-xs text-muted-foreground mt-1 leading-relaxed">{item.reason}</p>
                          </div>
                        </li>
                      ))}
                    </ul>
                  </div>
                ))}
              </div>

            </div>
          )}

        </div>
      </main>
      <FooterSection />
    </div>
  );
}
